### PR TITLE
[Refactor]: Front-end rewrite initialization

### PR DESCRIPTION
**Pull request by Anish-Agnihotri**
**Objective:**
Removes all existing front-end code, reinitializes via `create-react-app` and sets appropriate linting, style, and global conventions to ensure cleaner front-end development, moving forward.

**Structure**
```
├── jsconfig.json // Path setup, ignore
├── package-lock.json // ignore
├── package.json // ignore
├── public // Public files
│   ├── favicon.ico
│   └── index.html
└── src
    ├── components // Individual components
    │   └── Layout.js // Layout wrapper
    ├── containers // State containers for unstated-next
    ├── index.js
    ├── pages // Individual pages
    │   ├── Events.js
    │   ├── Home.js
    │   ├── Login.js
    │   ├── Performances.js
    │   └── Settings.js
    ├── routes.js // Navigation
    └── styles
        ├── components // Component styles
        ├── global.css // Global styles
        └── pages // Page styles
```

**Conventions:**
1. No class components, only functional components with React hooks.
2. No inline CSS, or text-based class names. Preference is to use CSS Modules.
3. Components stored in `/components`. Only `.js` files.
4. State containers stored in `/containers`. Only `.js` files. Import subcontainers to master `index.js`.
5. Pages stored in `/pages`. Only `.js` files.
6. Styles stored in `/styles`. Only `global.css` in root. Pages and components in respective folders as CSS Modules.
7. Descriptive comments across both `.js` and `.css` files.
8. Absolute imports only (i.e `pages/Home`, not `../../pages/Home`).
9. ES6 arrow functions only in local scope (i.e `const functionName = () => {}`, not `functionName() {}`).
10. Must [JSDoc](https://jsdoc.app/) all functions (your editor likely has inbuilt functionality).
11. External CSS or JS imports (unless via npm) must occur in `public/index.js`.

**JSDoc conventions**
Must JSDoc all functions. If function has `params` or `returns` values must include their type and description. For example:
```js
/**
  * Scroll to top of page
  */
const scrollToTop = () => {
   window.scrollTo(0, 0);
};

/**
  * Scroll to top of page
  * @param {Number} numA first number
  * @param {Number} numB second number
  * @returns {Number} sum of both numbers
  */
const calculateSum = (numA, numB) => {
   return numA + numB;
};
```

**Misc:**
If you use vscode, I would highly recommend setting up project settings to hide various files (namely: `*.json`, `.gitignore`, `.eslintcache`, `.eslintrc.yml`, `.prettierrc`). It will make your viewing experience more pleasurable.

### CODE REVIEW

**Review by thepenguinco — APPROVED** [review]
LGTM.  I'll copy your standards and conventions into Notion for reference.

**Review by OustanDing — APPROVED** [review]
Nice. Just had some questions:
1. Will `src/components` also be organized into subfolders based on the page that each component belongs to? How will components being used by multiple pages be organized in this folder?
2. Will there be somewhere for storing constants?

**Review by feng-eric — APPROVED** [review]
Looks good to me 😎

**Comment by Anish-Agnihotri** [comment]
@OustanDing Addressing your comments:
1. Yes, split into component folders by page. For cross-page components, they can stay at root.
2. Yes, I didn't have any constants to toss in just yet, but there will be a top level `utils/constants.js` likely.

**Comment by OustanDing** [comment]
@Anish-Agnihotri Cool, thanks for clarifying!

**Pull request merged**
